### ISSUE TITLE
Scroll position changes when other clients are editing

### ISSUE THREAD

**Issue by tommoor** [yjs/y-prosemirror#31]
### To Reproduce

- Create a doc long enough to scroll
- In one client place your cursor at the bottom of the screen and scroll to the top (common behavior when reading)
- In another client type at the top of the doc
- The scroll position in the first client will jump to the bottom

### Screencast

From the `y-prosemirror` demo site:

![Kapture 2020-12-08 at 15 01 08](https://user-images.githubusercontent.com/380914/101551749-6a6e6800-3966-11eb-9c31-361211601174.gif)

I tracked it down to this line – could you enlighten in which circumstances this is supposed to trigger? It feels like it would be fine if remote edits never caused the local scroll state to change.

https://github.com/yjs/y-prosemirror/blob/52116dd0333fa722b060b75ed86fb81f361b9e9a/src/plugins/sync-plugin.js#L344-L346

**Comment by dmonad** [comment]
I can't reproduce this issue in `Chrome Version 87.0.4280.66 (Official Build) (64-bit)`.

The code you mentioned scrolls the window to the current editing position when a remote change happens IF the cursor is currently in view. This prevents weird scrolling behavior when a user is adding/removing a lot of content at the beginning of the document.

**Comment by tommoor** [comment]
In which case the "if cursor is in view" logic must not be correct

**Comment by dmonad** [comment]
Apparantly. But your comment doesn't help me to fix the problem. As said, I can't reproduce the issue using the description you gave me.

**Comment by tommoor** [comment]
Some more debugging, when it reaches`isDomSelectionInView` the documentElement is actually just the `html` tag, so seems like it would be safe to guard that this isn't the case?

![image](https://user-images.githubusercontent.com/380914/101700704-6019a000-3a32-11eb-8f67-3e4e43e2df0f.png)

**Comment by dmonad** [comment]
That is intended. Maybe the check fails because `documentElement.clientHeight` is the full height of the website? That is why it is important to specify which browser / which OS you are using... 

In your environment, is that different from `window.innerHeight`? innerHeight might be more appropriate to use here.

**Comment by tommoor** [comment]
> That is why it is important to specify which browser / which OS you are using...

Totally agreed, that information wasn't requested in the template previously though and I thought it would be relatively clear in the gif that it's Chrome on macOS.
